const { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelSelectMenuBuilder, RoleSelectMenuBuilder, StringSelectMenuBuilder, StringSelectMenuOptionBuilder, ChannelType } = require("discord.js");
const { CATEGORIES, CATEGORY_ORDER, getSetting, currentValue, createHomeEmbed, createCategoryEmbed, createSettingEmbed } = require("../embeds/setup");
const { saveData } = require("../utils/database");
const sessions = new Map();
const TTL = 30 * 60 * 1000;
function key(i){return i.guildId+":"+i.user.id;}
function saveSession(i,s){sessions.set(key(i),{...s,expiresAt:Date.now()+TTL});}
function getSession(i){const s=sessions.get(key(i)); if(!s)return null; if(Date.now()>s.expiresAt){sessions.delete(key(i));return null;} return s;}
function admin(i){return i.memberPermissions?.has("Administrator");}
function check(i){if(!admin(i))return "❌ Only administrators can use this setup panel."; const s=getSession(i); if(!s)return "❌ This setup session expired. Run `/setup` again."; if(s.messageId&&i.message?.id!==s.messageId)return "❌ This is not your active setup panel. Run `/setup` again."; return s;}
function homeComponents(){const s=new StringSelectMenuBuilder().setCustomId("setup_category").setPlaceholder("Choose what you want to edit").addOptions(CATEGORY_ORDER.map(k=>{const c=CATEGORIES[k];return new StringSelectMenuOptionBuilder().setLabel(c.label).setDescription(c.description).setEmoji(c.emoji).setValue(k);}));return [new ActionRowBuilder().addComponents(s),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("setup_done").setLabel("DONE").setStyle(ButtonStyle.Secondary))];}
function categoryComponents(data,k){const c=CATEGORIES[k];const s=new StringSelectMenuBuilder().setCustomId("setup_setting:"+k).setPlaceholder("Choose one setting to edit").addOptions(c.settings.map(x=>new StringSelectMenuOptionBuilder().setLabel(x.label).setDescription((x.type==="role"?"Role":"Channel")+" • "+(currentValue(data,x.key)?"Configured":"Not set")).setValue(x.key)));return [new ActionRowBuilder().addComponents(s),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("setup_home").setLabel("← CATEGORIES").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("setup_done").setLabel("DONE").setStyle(ButtonStyle.Success))];}
function valueComponents(c,s){const id="setup_value:"+c+":"+s.key;const sel=s.type==="role"?new RoleSelectMenuBuilder().setCustomId(id).setPlaceholder("Select the "+s.label+" role").setMinValues(1).setMaxValues(1):new ChannelSelectMenuBuilder().setCustomId(id).setPlaceholder("Select the "+s.label+" channel").setMinValues(1).setMaxValues(1).addChannelTypes(ChannelType.GuildText);return [new ActionRowBuilder().addComponents(sel),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("setup_back:"+c).setLabel("← BACK").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("setup_home").setLabel("CATEGORIES").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("setup_done").setLabel("DONE").setStyle(ButtonStyle.Success))];}
async function startSetup(i,data){if(!admin(i)){await i.reply({content:"❌ You need **Administrator** permission to use the setup panel.",ephemeral:true});return;}const r=await i.reply({embeds:[createHomeEmbed()],components:homeComponents(),ephemeral:false,fetchReply:true});saveSession(i,{messageId:r.id,category:null,setting:null});}
async function handleSetupButton(i,data){if(!i.customId.startsWith("setup_"))return false;const s=check(i);if(typeof s==="string"){await i.reply({content:s,ephemeral:true});return true;}if(i.customId==="setup_done"){sessions.delete(key(i));await i.update({embeds:[createHomeEmbed().setDescription("✅ **Setup finished.**\n\nRun `/setup` again any time you want to change a setting.")],components:[]});return true;}if(i.customId==="setup_home"){s.category=null;s.setting=null;saveSession(i,s);await i.update({embeds:[createHomeEmbed()],components:homeComponents()});return true;}if(i.customId.startsWith("setup_back:")){const c=i.customId.split(":")[1];s.category=c;s.setting=null;saveSession(i,s);await i.update({embeds:[createCategoryEmbed(data,c)],components:categoryComponents(data,c)});return true;}return true;}
async function handleSetupSelect(i,data){if(!i.customId.startsWith("setup_"))return false;const s=check(i);if(typeof s==="string"){await i.reply({content:s,ephemeral:true});return true;}if(i.customId==="setup_category"){const c=i.values[0];if(!CATEGORIES[c]){await i.reply({content:"❌ Invalid setup category.",ephemeral:true});return true;}s.category=c;s.setting=null;saveSession(i,s);await i.update({embeds:[createCategoryEmbed(data,c)],components:categoryComponents(data,c)});return true;}if(i.customId.startsWith("setup_setting:")){const c=i.customId.split(":")[1], k=i.values[0], setting=getSetting(c,k);if(!setting){await i.reply({content:"❌ Invalid setup setting.",ephemeral:true});return true;}s.category=c;s.setting=k;saveSession(i,s);await i.update({embeds:[createSettingEmbed(data,c,k)],components:valueComponents(c,setting)});return true;}if(i.customId.startsWith("setup_value:")){const p=i.customId.split(":"),c=p[1],k=p[2],setting=getSetting(c,k),v=i.values?.[0];if(!setting||!v){await i.reply({content:"❌ Invalid setup value.",ephemeral:true});return true;}apply(data,k,v);await saveData(data);s.category=c;s.setting=null;saveSession(i,s);await i.update({embeds:[createCategoryEmbed(data,c,"✅ **"+setting.label+" updated and saved.**")],components:categoryComponents(data,c)});return true;}return false;}
function apply(data,k,v){if(k==="helpdesk_channel")data.config.helpDesk.channelId=v;else if(k==="war_role")data.config.helpDesk.warRoleId=v;else if(k==="backup_role")data.config.helpDesk.backupRoleId=v;else if(k==="rank_registration")data.config.rank.registrationChannelId=v;else if(k==="rank_review")data.config.rank.reviewChannelId=v;else if(k==="rank_history")data.config.rank.historyChannelId=v;else if(k==="leaderboard_channel")data.config.rank.leaderboardChannelId=v;else if(k.startsWith("rank_role_"))data.config.rank.rankRoleIds[k.replace("rank_role_","")]=v;data.rankConfig={...data.rankConfig,registrationChannelId:data.config.rank.registrationChannelId,reviewChannelId:data.config.rank.reviewChannelId,historyChannelId:data.config.rank.historyChannelId,rankRoleIds:{...(data.rankConfig.rankRoleIds||{}),...(data.config.rank.rankRoleIds||{})}};}
module.exports={startSetup,handleSetupButton,handleSetupSelect};