const{ActionRowBuilder,ButtonBuilder,ButtonStyle,ChannelSelectMenuBuilder,RoleSelectMenuBuilder,StringSelectMenuBuilder,StringSelectMenuOptionBuilder,ChannelType}=require("discord.js");
const{CATEGORIES,CATEGORY_ORDER,getSetting,currentValue,createHomeEmbed,createCategoryEmbed,createSettingEmbed}=require("../embeds/setup");const{saveData}=require("../utils/database");const sessions=new Map();const sid=i=>i.guildId+":"+i.user.id;
const admin=i=>i.memberPermissions?.has("Administrator");function check(i){if(!admin(i))return"❌ Only administrators can use this setup panel.";const s=sessions.get(sid(i));if(!s)return"❌ Setup session expired. Run `/setup` again.";if(s.messageId!==i.message?.id)return"❌ This is not your active setup panel.";return s}
function home(){return[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId("setup_category").setPlaceholder("Choose what you want to edit").addOptions(CATEGORY_ORDER.map(k=>{const c=CATEGORIES[k];return new StringSelectMenuOptionBuilder().setLabel(c.label).setDescription(c.description).setEmoji(c.emoji).setValue(k)}))),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("setup_done").setLabel("DONE").setStyle(ButtonStyle.Secondary))]}
function cat(d,k){const c=CATEGORIES[k],m=new StringSelectMenuBuilder().setCustomId("setup_setting:"+k).setPlaceholder("Choose one setting to edit").addOptions(c.settings.map(s=>new StringSelectMenuOptionBuilder().setLabel(s.label).setDescription((s.type==="role"?"Role":"Channel")+" • "+(currentValue(d,s.key)?"Configured":"Not set")).setValue(s.key)));return[new ActionRowBuilder().addComponents(m),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("setup_home").setLabel("← CATEGORIES").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("setup_done").setLabel("DONE").setStyle(ButtonStyle.Success))]}
function val(c,s){const m=s.type==="role"?new RoleSelectMenuBuilder():new ChannelSelectMenuBuilder().addChannelTypes(ChannelType.GuildText);m.setCustomId("setup_value:"+c+":"+s.key).setPlaceholder("Select "+s.label).setMinValues(1).setMaxValues(1);return[new ActionRowBuilder().addComponents(m),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("setup_back:"+c).setLabel("← BACK").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("setup_home").setLabel("CATEGORIES").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("setup_done").setLabel("DONE").setStyle(ButtonStyle.Success))]}
async function startSetup(i,d){if(!admin(i))return i.reply({content:"❌ You need **Administrator** permission.",ephemeral:true});const r=await i.reply({embeds:[createHomeEmbed()],components:home(),fetchReply:true});sessions.set(sid(i),{messageId:r.id})}
async function handleSetupButton(i,d){if(!i.customId.startsWith("setup_"))return false;if(i.isStringSelectMenu?.()||i.isRoleSelectMenu?.()||i.isChannelSelectMenu?.())return handleSetupSelect(i,d);const s=check(i);if(typeof s==="string"){await i.reply({content:s,ephemeral:true});return true}if(i.customId==="setup_done"){sessions.delete(sid(i));await i.update({embeds:[createHomeEmbed().setDescription("✅ **Setup finished.** Run `/setup` again to edit settings.")],components:[]});return true}if(i.customId==="setup_home"){await i.update({embeds:[createHomeEmbed()],components:home()});return true}if(i.customId.startsWith("setup_back:")){const k=i.customId.split(":")[1];await i.update({embeds:[createCategoryEmbed(d,k)],components:cat(d,k)});return true}return true}
async function handleSetupSelect(i,d){const s=check(i);if(typeof s==="string"){await i.reply({content:s,ephemeral:true});return true}if(i.customId==="setup_category"){const k=i.values[0];await i.update({embeds:[createCategoryEmbed(d,k)],components:cat(d,k)});return true}if(i.customId.startsWith("setup_setting:")){const p=i.customId.split(":"),k=p[1],q=i.values[0],set=getSetting(k,q);await i.update({embeds:[createSettingEmbed(d,k,q)],components:val(k,set)});return true}if(i.customId.startsWith("setup_value:")){const p=i.customId.split(":"),k=p[1],q=p[2],set=getSetting(k,q);apply(d,q,i.values[0]);await saveData(d);await i.update({embeds:[createCategoryEmbed(d,k,"✅ **"+set.label+" updated and saved.**")],components:cat(d,k)});return true}return false}
function apply(d,k,v){if(k==="helpdesk_channel")d.config.helpDesk.channelId=v;else if(k==="war_role")d.config.helpDesk.warRoleId=v;else if(k==="backup_role")d.config.helpDesk.backupRoleId=v;else if(k==="rank_registration")d.config.rank.registrationChannelId=v;else if(k==="rank_review")d.config.rank.reviewChannelId=v;else if(k==="rank_history")d.config.rank.historyChannelId=v;else if(k==="leaderboard_channel")d.config.rank.leaderboardChannelId=v;else if(k.startsWith("rank_role_"))d.config.rank.rankRoleIds[k.slice(10)]=v;d.rankConfig={...d.rankConfig,registrationChannelId:d.config.rank.registrationChannelId,reviewChannelId:d.config.rank.reviewChannelId,historyChannelId:d.config.rank.historyChannelId,rankRoleIds:{...(d.rankConfig.rankRoleIds||{}),...(d.config.rank.rankRoleIds||{})}}}
module.exports={startSetup,handleSetupButton,handleSetupSelect};